# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DataArchiver < Formula
  desc "Archive database data to object storage with parallel processing. Currently supports PostgreSQL input and S3-compatible output."
  homepage "https://github.com/airframesio/data-archiver"
  version "1.4.2"
  license "MIT"

  depends_on "postgresql" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/airframesio/data-archiver/releases/download/v1.4.2/data-archiver-1.4.2-darwin-amd64.tar.gz"
      sha256 "cef4b9b724eaaefb664b50e553e83dc5c8cb7d2094b69f487628d083ccf0a564"

      def install
        bin.install "data-archiver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/airframesio/data-archiver/releases/download/v1.4.2/data-archiver-1.4.2-darwin-arm64.tar.gz"
      sha256 "ac68751009f898eb1e10ddd3fdb438a6fdf24670a8c97e93950b62a9cdc94d8c"

      def install
        bin.install "data-archiver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/airframesio/data-archiver/releases/download/v1.4.2/data-archiver-1.4.2-linux-amd64.tar.gz"
      sha256 "136668417ef0e63e4c3a3bd87cde306da28a70ac1341d86b04c16587ceae7dd2"
      def install
        bin.install "data-archiver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/airframesio/data-archiver/releases/download/v1.4.2/data-archiver-1.4.2-linux-arm64.tar.gz"
      sha256 "28441ad9a6f37f34576dc03a75c48f4e3b3e091cc0b280fd3e1c844e1630ebc1"
      def install
        bin.install "data-archiver"
      end
    end
  end

  test do
    system "#{bin}/data-archiver", "--version"
    assert_match version.to_s, shell_output("#{bin}/data-archiver --version 2>&1")
  end
end
