# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PostgresqlArchiver < Formula
  desc "Archive PostgreSQL partition data to object storage with parallel processing"
  homepage "https://github.com/airframesio/postgresql-archiver"
  version "1.0.3"
  license "MIT"

  depends_on "postgresql" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/airframesio/postgresql-archiver/releases/download/v1.0.3/postgresql-archiver-1.0.3-darwin-amd64.tar.gz"
      sha256 "55ef5e83871c9a89d52657689170565dd25de4a194574d02ec73c992d01fbb83"

      def install
        bin.install "postgresql-archiver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/airframesio/postgresql-archiver/releases/download/v1.0.3/postgresql-archiver-1.0.3-darwin-arm64.tar.gz"
      sha256 "84c3a4f8b39746705ee0cfe5d8ddfff08d41c83e3c48417c70d074806047b655"

      def install
        bin.install "postgresql-archiver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/airframesio/postgresql-archiver/releases/download/v1.0.3/postgresql-archiver-1.0.3-linux-amd64.tar.gz"
      sha256 "0e6fd71a06167c0d4a0b47301bfb508917588424d97a2985309b9494ffede576"
      def install
        bin.install "postgresql-archiver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/airframesio/postgresql-archiver/releases/download/v1.0.3/postgresql-archiver-1.0.3-linux-arm64.tar.gz"
      sha256 "fa400fde64faf5de61042f7e98d4da06baeaf534819aba13c372f724a639a6ba"
      def install
        bin.install "postgresql-archiver"
      end
    end
  end

  test do
    system "#{bin}/postgresql-archiver", "--version"
    assert_match version.to_s, shell_output("#{bin}/postgresql-archiver --version 2>&1")
  end
end
