# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PostgresqlArchiver < Formula
  desc "Archive PostgreSQL partition data to object storage with parallel processing"
  homepage "https://github.com/airframesio/postgresql-archiver"
  version "1.1.0"
  license "MIT"

  depends_on "postgresql" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/airframesio/postgresql-archiver/releases/download/v1.1.0/postgresql-archiver-1.1.0-darwin-amd64.tar.gz"
      sha256 "2d8d9c5bfd3277d27cdf1a95438713de2741e553544f68bcb2acca4399b31160"

      def install
        bin.install "postgresql-archiver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/airframesio/postgresql-archiver/releases/download/v1.1.0/postgresql-archiver-1.1.0-darwin-arm64.tar.gz"
      sha256 "14085847962224ba34ae3bbf74e7ac508c4f962bbdb34875156a97a3e0c61e0f"

      def install
        bin.install "postgresql-archiver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/airframesio/postgresql-archiver/releases/download/v1.1.0/postgresql-archiver-1.1.0-linux-amd64.tar.gz"
      sha256 "1f969f6b03fc1d862458ed035442688c777ec8387a0a573f18d69da8943e9afc"
      def install
        bin.install "postgresql-archiver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/airframesio/postgresql-archiver/releases/download/v1.1.0/postgresql-archiver-1.1.0-linux-arm64.tar.gz"
      sha256 "179164da6db94d3096fbf69655a64ecc289c62e2e2007a656cf4e6edfeed9cdf"
      def install
        bin.install "postgresql-archiver"
      end
    end
  end

  test do
    system "#{bin}/postgresql-archiver", "--version"
    assert_match version.to_s, shell_output("#{bin}/postgresql-archiver --version 2>&1")
  end
end
